#!/bin/bash
### BEGIN INIT INFO
### END INIT INFO
 
#The location of the IRC Bot binary e.g. /opt/uas/ircbotd.py
IRC_BOTD="/opt/uas/Occupancy/ocs.sh"
#Are there options/switches for the IRC bot? e.g. -D -l /var/log/irc_bot.log etc..
OPTIONS=""
#Path to the bot's PID file e.g. /path/to/bot.pid
pid_path=/var/run/ocs.pid
 
do_start()
{
        if [ -f $pid_path ]; then
                echo "Occupancy is already running, or it crashed and the pid file still exists! Try stop/restart, or removing the PID file first."
        else
                echo "Starting UAS Occupancy."
                nohup $IRC_BOTD $OPTIONS &> /opt/uas/Occupancy.log &
                if [ $? -eq 0 ]; then
                        echo "UAS Occupancy successfully started."
                        logger "UAS Occupancy started."
                else
                        echo "UAS Occupancy failed to start!"
                fi
        fi
    return 0
}
 
do_status()
{
        if [ -f $pid_path ]; then
                echo "UAS Occupancy is running with a pid of `cat $pid_path`"
        else
                echo "UAS Occupancy is not running, or has not generated a pid file."
        fi
        return 0
}
 
do_stop()
{
    echo "Stopping UAS IRC bot"
        if [ -f $pid_path ]; then
                kill -6 `cat $pid_path` 2> /dev/null
                if [ $? -eq 0 ]; then
                        echo "UAS Occupancy stopped."
                        logger "Gracefully killed UAS Occupancy."
                else
                        echo "UAS Occupancy could not be killed! (Permissions? Already dead? Pid file missing?)"
                fi
        else
                echo "UAS Occupancy is not running, or has not generated a pid file."
        fi
    rm $pid_path
    return 0
}
 
case "$1" in
 start)
    do_start
    ;;
 stop)
    do_stop
    ;;
 restart)
    do_stop
    sleep 1
    do_start
    ;;
 status)
        do_status
        ;;
 *)
    echo "Usage: Occupancy {start|stop|restart|status}" >&2
    exit 3
    ;;
esac
exit 0
